import { useCallback, useEffect, useState } from 'react';
import type { ActivityCursor, ActivityPage, ActivityScope, PaymentRequest } from '../../shared/contracts/api';
import type { Currency, Player, Transaction } from '../../shared/types/monopoly';
import { monopolyBankApi } from '../api/monopoly-bank-api';
import { Dialog } from '../components/Dialog';
import { useLanguage } from '../i18n/language-context';
import { formatMoney } from '../utils/money';
import { transactionAmount, transactionDescription } from '../utils/transaction-history';

export function ActivityScreen({ gameId, players, currency, liveTransactions, onClose }: { gameId: string; players: Player[]; currency: Currency; liveTransactions: Transaction[]; onClose: () => void }) {
  const { language, locale, t } = useLanguage();
  const [scope, setScope] = useState<ActivityScope>('ALL'); const [page, setPage] = useState<ActivityPage>({ transactions: [], paymentRequests: [], nextCursor: null }); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const load = useCallback(async (append: boolean, cursor?: ActivityCursor | null) => { setLoading(true); setError(false); try { const next = await monopolyBankApi.getActivity(gameId, scope, append ? encodeCursor(cursor ?? null) : undefined); setPage((current) => append ? { ...next, transactions: mergeTransactions(current.transactions, next.transactions), paymentRequests: mergeRequests(current.paymentRequests, next.paymentRequests) } : next); } catch { setError(true); } finally { setLoading(false); } }, [gameId, scope]);
  useEffect(() => { void load(false); }, [load]);
  useEffect(() => { if (scope === 'PENDING' || liveTransactions.length === 0) return; setPage((current) => ({ ...current, transactions: mergeTransactions(liveTransactions, current.transactions) })); }, [liveTransactions, scope]);
  const items = scope === 'PENDING' ? page.paymentRequests : page.transactions;
  return <Dialog title={t('activity')} closeLabel={t('closeDialog', { title: t('activity') })} onClose={onClose} className="activity-dialog"><div className="activity-tabs" role="tablist" aria-label={t('activity')}><Tab scope="ALL" label={t('activityAll')} /><Tab scope="MINE" label={t('activityMine')} /><Tab scope="PENDING" label={t('activityPending')} /></div>{error && <p className="notice notice-error" role="alert">{t('unableLoadHistory')}</p>}<ol className="activity-ledger">{items.map((item) => 'state' in item ? <PendingRow key={item.id} request={item} players={players} currency={currency} locale={locale} /> : <li key={item.id}><strong>{transactionDescription(item, players, language)}</strong><span>{transactionAmount(item, currency, language)}</span><time>{new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(item.createdAt))}</time>{item.comment !== null && <em>{item.comment}</em>}</li>)}</ol>{!loading && items.length === 0 && <p className="muted">{scope === 'PENDING' ? t('noPendingActivity') : t('noActivity')}</p>}{loading && <p role="status" className="muted">{t('loadingGame')}</p>}{page.nextCursor !== null && <button className="button button-secondary" type="button" disabled={loading} onClick={() => void load(true, page.nextCursor)}>{t('loadMore')}</button>}</Dialog>;
  function Tab({ scope: value, label }: { scope: ActivityScope; label: string }) { return <button type="button" role="tab" aria-selected={scope === value} className="button button-quiet" onClick={() => setScope(value)}>{label}</button>; }
}
function PendingRow({ request, players, currency, locale }: { request: PaymentRequest; players: Player[]; currency: Currency; locale: string }) { const { t } = useLanguage(); const creator = players.find((player) => player.id === request.creatorPlayerId)?.name ?? t('selectedPlayer'); const approver = players.find((player) => player.id === request.approverPlayerId)?.name ?? t('selectedPlayer'); return <li className="activity-pending"><strong>{t('pendingPayment')}: {creator} → {approver}</strong><span>{formatMoney(request.amount, currency)}</span><time>{new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(request.createdAt))}</time>{request.comment !== null && <em>{request.comment}</em>}</li>; }
function encodeCursor(cursor: ActivityCursor | null): string | undefined { return cursor === null ? undefined : btoa(JSON.stringify(cursor)); }
function mergeTransactions(first: readonly Transaction[], second: readonly Transaction[]): Transaction[] { return [...first, ...second].filter((item, index, all) => all.findIndex((candidate) => candidate.id === item.id) === index); }
function mergeRequests(first: readonly PaymentRequest[], second: readonly PaymentRequest[]): PaymentRequest[] { return [...first, ...second].filter((item, index, all) => all.findIndex((candidate) => candidate.id === item.id) === index); }
