import { useState, type FormEvent } from 'react';
import type { UserProfile } from '../../shared/contracts/api';
import { monopolyBankApi } from '../api/monopoly-bank-api';

export function AuthPage({ onAuthenticated }: { onAuthenticated: (profile: UserProfile) => void }) {
  const [registering, setRegistering] = useState(false); const [nickname, setNickname] = useState(''); const [avatar, setAvatar] = useState('🎩'); const [password, setPassword] = useState(''); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { onAuthenticated(registering ? await monopolyBankApi.register({ nickname, avatar, password }) : await monopolyBankApi.login({ nickname, password })); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to authenticate.'); } finally { setBusy(false); } };
  return <main className="page page-narrow auth-page"><section className="banknote-panel auth-card"><div className="auth-card-heading"><span className="auth-card-mark" aria-hidden="true">MB</span><div><p className="eyebrow">Monopoly Bank</p><h1>{registering ? 'Create your account' : 'Welcome back'}</h1></div></div><p className="lede">{registering ? 'Set up a private account for your games and statistics.' : 'Sign in to resume your private games.'}</p><form className="game-form auth-form" onSubmit={(event) => void submit(event)}><label>Nickname<input value={nickname} minLength={2} maxLength={40} autoComplete="username" placeholder="Your nickname" onChange={(event) => setNickname(event.target.value)} required /></label>{registering && <label>Avatar<select value={avatar} onChange={(event) => setAvatar(event.target.value)}>{['🎩', '🚗', '🐶', '🚢', '🎲', '💎'].map((item) => <option key={item}>{item}</option>)}</select></label>}<label>Password<input type="password" value={password} minLength={10} maxLength={256} autoComplete={registering ? 'new-password' : 'current-password'} placeholder="At least 10 characters" onChange={(event) => setPassword(event.target.value)} required /></label>{error !== null && <p className="notice notice-error">{error}</p>}<button className="button button-primary" disabled={busy}>{busy ? 'Please wait…' : registering ? 'Create account' : 'Sign in'}</button></form><div className="auth-card-footer"><span>{registering ? 'Already have an account?' : 'New to Monopoly Bank?'}</span><button className="button button-quiet" type="button" onClick={() => setRegistering(!registering)}>{registering ? 'Sign in' : 'Create an account'}</button></div></section></main>;
}
