import { useState, type FormEvent } from 'react';
import type { UserProfile } from '../../shared/contracts/api';
import { monopolyBankApi } from '../api/monopoly-bank-api';
import { Avatar, AvatarPicker } from '../components/AvatarPicker';
import { apiErrorMessage } from '../i18n/api-errors';
import { useLanguage } from '../i18n/language-context';

export function ProfilePage({ profile, onUpdated, onBack }: { profile: UserProfile; onUpdated: (profile: UserProfile) => void; onBack: () => void }) {
  const { t } = useLanguage();
  const [nickname, setNickname] = useState(profile.nickname); const [avatar, setAvatar] = useState(profile.avatar); const [error, setError] = useState<unknown>(null); const [saved, setSaved] = useState(false); const [saving, setSaving] = useState(false);
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(null); setSaved(false); try { onUpdated(await monopolyBankApi.updateProfile({ nickname, avatar })); setSaved(true); } catch (caught) { setError(caught); } finally { setSaving(false); } };
  return <main className="page page-narrow profile-page"><section className="page-heading"><div><p className="eyebrow">{t('playerProfile')}</p><h1>{t('playerProfile')}</h1><p className="lede">{t('profileDescription')}</p></div><button className="button button-quiet" type="button" onClick={onBack}>{t('savedGames')}</button></section><section className="banknote-panel profile-card"><div className="profile-summary"><Avatar avatar={avatar} label={nickname} className="profile-avatar" /><div><h2>{nickname}</h2><p className="muted">{t('playerProfile')}</p></div></div><dl className="profile-statistics"><div><dt>{t('gamesPlayed')}</dt><dd>{profile.gamesPlayed}</dd></div><div><dt>{t('gamesWon')}</dt><dd>{profile.gamesWon}</dd></div><div><dt>{t('winRate')}</dt><dd>{Math.round(profile.winRate * 100)}%</dd></div></dl><form className="game-form profile-form" onSubmit={(event) => void save(event)}><label>{t('nickname')}<input value={nickname} minLength={2} maxLength={40} onChange={(event) => setNickname(event.target.value)} required /></label><AvatarPicker avatar={avatar} onChange={setAvatar} label={t('avatar')} uploadLabel={t('avatarUpload')} uploadHint={t('avatarUploadHint')} invalidImageMessage={t('avatarUploadError')} allowUpload />{error !== null && <p className="notice notice-error" role="alert">{apiErrorMessage(error, t, 'unableUpdateProfile')}</p>}{saved && <p className="notice notice-success" role="status">{t('profileUpdated')}</p>}<button className="button button-primary" disabled={saving}>{saving ? t('savingProfile') : t('saveProfile')}</button></form></section></main>;
}
